version: '3.7'
services:
    web:
        container_name: ${PROJECT_NAME}-web
        image: webdevops/php-apache-dev:7.4
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/app/public
            - WEB_DOCUMENT_INDEX=index.php
            - PHP_MAX_EXECUTION_TIME=86400
        ports:
            - '${DOCKER_APP_PORT}:80'
        networks:
            - ${PROJECT_NAME}-network
        depends_on:
            - db
    
    db:
        image: mariadb:10.3
        container_name: ${PROJECT_NAME}-db
        restart: on-failure
        ports:
            - "${DOCKER_MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        networks:
            - ${PROJECT_NAME}-network
        volumes:
            - ./.docker/data:/var/lib_/mysql
    
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}-phpmyadmin
        restart: always
        ports:
            - '${DOCKER_PHPMYADMIN_PORT}:80'
        environment:
            PMA_HOST: ${PROJECT_NAME}-db
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        networks:
            - ${PROJECT_NAME}-network

networks:
    bycoders-network:
        driver: bridge